package com.bob.p2p.dao;

import com.bob.p2p.model.loan.BidInfoEntity;

public interface BidInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    int insert(BidInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    int insertSelective(BidInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    BidInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    int updateByPrimaryKeySelective(BidInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Thu May 27 12:24:17 CST 2021
     */
    int updateByPrimaryKey(BidInfoEntity record);
}