package com.bob.p2p.dao;

import com.bob.p2p.model.FinanceAccountEntity;

public interface FinanceAccountEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int insert(FinanceAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int insertSelective(FinanceAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    FinanceAccountEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int updateByPrimaryKeySelective(FinanceAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int updateByPrimaryKey(FinanceAccountEntity record);
}