package com.bob.p2p.dao;

import com.bob.p2p.model.IncomeRecordEntity;

public interface IncomeRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    int insert(IncomeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    int insertSelective(IncomeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    IncomeRecordEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    int updateByPrimaryKeySelective(IncomeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    int updateByPrimaryKey(IncomeRecordEntity record);
}