package com.bob.p2p.dao;

import com.bob.p2p.model.RechargeRecordEntity;

public interface RechargeRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int insert(RechargeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int insertSelective(RechargeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    RechargeRecordEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int updateByPrimaryKeySelective(RechargeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Mon May 31 10:44:41 CST 2021
     */
    int updateByPrimaryKey(RechargeRecordEntity record);
}