package com.bob.p2p.model;

import java.util.Date;

public class BorromerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.name
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.sex
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.birthday
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.education
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.marital
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer marital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.address
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.industry
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.workCity
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer workcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.workYear
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String workyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.yearSalary
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String yearsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.housing
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer housing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.car
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer car;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.borrowReason
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String borrowreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.borrowMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Double borrowmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.borrowTerm
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Double borrowterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_borrower_info.idcardAuth
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer idcardauth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.id
     *
     * @return the value of b_borrower_info.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.id
     *
     * @param id the value for b_borrower_info.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.name
     *
     * @return the value of b_borrower_info.name
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.name
     *
     * @param name the value for b_borrower_info.name
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.sex
     *
     * @return the value of b_borrower_info.sex
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.sex
     *
     * @param sex the value for b_borrower_info.sex
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.birthday
     *
     * @return the value of b_borrower_info.birthday
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.birthday
     *
     * @param birthday the value for b_borrower_info.birthday
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.education
     *
     * @return the value of b_borrower_info.education
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.education
     *
     * @param education the value for b_borrower_info.education
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.marital
     *
     * @return the value of b_borrower_info.marital
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getMarital() {
        return marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.marital
     *
     * @param marital the value for b_borrower_info.marital
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setMarital(Integer marital) {
        this.marital = marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.address
     *
     * @return the value of b_borrower_info.address
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.address
     *
     * @param address the value for b_borrower_info.address
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.industry
     *
     * @return the value of b_borrower_info.industry
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.industry
     *
     * @param industry the value for b_borrower_info.industry
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.workCity
     *
     * @return the value of b_borrower_info.workCity
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getWorkcity() {
        return workcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.workCity
     *
     * @param workcity the value for b_borrower_info.workCity
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setWorkcity(Integer workcity) {
        this.workcity = workcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.workYear
     *
     * @return the value of b_borrower_info.workYear
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getWorkyear() {
        return workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.workYear
     *
     * @param workyear the value for b_borrower_info.workYear
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setWorkyear(String workyear) {
        this.workyear = workyear == null ? null : workyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.yearSalary
     *
     * @return the value of b_borrower_info.yearSalary
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getYearsalary() {
        return yearsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.yearSalary
     *
     * @param yearsalary the value for b_borrower_info.yearSalary
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setYearsalary(String yearsalary) {
        this.yearsalary = yearsalary == null ? null : yearsalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.housing
     *
     * @return the value of b_borrower_info.housing
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getHousing() {
        return housing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.housing
     *
     * @param housing the value for b_borrower_info.housing
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setHousing(Integer housing) {
        this.housing = housing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.car
     *
     * @return the value of b_borrower_info.car
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.car
     *
     * @param car the value for b_borrower_info.car
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setCar(Integer car) {
        this.car = car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.borrowReason
     *
     * @return the value of b_borrower_info.borrowReason
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getBorrowreason() {
        return borrowreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.borrowReason
     *
     * @param borrowreason the value for b_borrower_info.borrowReason
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowreason(String borrowreason) {
        this.borrowreason = borrowreason == null ? null : borrowreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.borrowMoney
     *
     * @return the value of b_borrower_info.borrowMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Double getBorrowmoney() {
        return borrowmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.borrowMoney
     *
     * @param borrowmoney the value for b_borrower_info.borrowMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowmoney(Double borrowmoney) {
        this.borrowmoney = borrowmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.borrowTerm
     *
     * @return the value of b_borrower_info.borrowTerm
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Double getBorrowterm() {
        return borrowterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.borrowTerm
     *
     * @param borrowterm the value for b_borrower_info.borrowTerm
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowterm(Double borrowterm) {
        this.borrowterm = borrowterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_borrower_info.idcardAuth
     *
     * @return the value of b_borrower_info.idcardAuth
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getIdcardauth() {
        return idcardauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_borrower_info.idcardAuth
     *
     * @param idcardauth the value for b_borrower_info.idcardAuth
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setIdcardauth(Integer idcardauth) {
        this.idcardauth = idcardauth;
    }
}