package com.bob.p2p.model;

public class CreditorRights {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_creditor_rights.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_creditor_rights.borrow_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Double borrowMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_creditor_rights.borrow_cycle
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer borrowCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_creditor_rights.borrow_purpose
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer borrowPurpose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_creditor_rights.id
     *
     * @return the value of b_creditor_rights.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_creditor_rights.id
     *
     * @param id the value for b_creditor_rights.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_creditor_rights.borrow_money
     *
     * @return the value of b_creditor_rights.borrow_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Double getBorrowMoney() {
        return borrowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_creditor_rights.borrow_money
     *
     * @param borrowMoney the value for b_creditor_rights.borrow_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowMoney(Double borrowMoney) {
        this.borrowMoney = borrowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_creditor_rights.borrow_cycle
     *
     * @return the value of b_creditor_rights.borrow_cycle
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getBorrowCycle() {
        return borrowCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_creditor_rights.borrow_cycle
     *
     * @param borrowCycle the value for b_creditor_rights.borrow_cycle
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowCycle(Integer borrowCycle) {
        this.borrowCycle = borrowCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_creditor_rights.borrow_purpose
     *
     * @return the value of b_creditor_rights.borrow_purpose
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getBorrowPurpose() {
        return borrowPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_creditor_rights.borrow_purpose
     *
     * @param borrowPurpose the value for b_creditor_rights.borrow_purpose
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setBorrowPurpose(Integer borrowPurpose) {
        this.borrowPurpose = borrowPurpose;
    }
}