package com.bob.p2p.model;

import java.util.Date;

public class DealRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_no
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Long dealNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_status
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Double dealMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_time
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_type
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer dealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_deal_record.deal_desc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String dealDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.id
     *
     * @return the value of b_deal_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.id
     *
     * @param id the value for b_deal_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.uid
     *
     * @return the value of b_deal_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.uid
     *
     * @param uid the value for b_deal_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_no
     *
     * @return the value of b_deal_record.deal_no
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Long getDealNo() {
        return dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_no
     *
     * @param dealNo the value for b_deal_record.deal_no
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealNo(Long dealNo) {
        this.dealNo = dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_status
     *
     * @return the value of b_deal_record.deal_status
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_status
     *
     * @param dealStatus the value for b_deal_record.deal_status
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_money
     *
     * @return the value of b_deal_record.deal_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Double getDealMoney() {
        return dealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_money
     *
     * @param dealMoney the value for b_deal_record.deal_money
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealMoney(Double dealMoney) {
        this.dealMoney = dealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_time
     *
     * @return the value of b_deal_record.deal_time
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_time
     *
     * @param dealTime the value for b_deal_record.deal_time
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_type
     *
     * @return the value of b_deal_record.deal_type
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_type
     *
     * @param dealType the value for b_deal_record.deal_type
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealType(Integer dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_deal_record.deal_desc
     *
     * @return the value of b_deal_record.deal_desc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getDealDesc() {
        return dealDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_deal_record.deal_desc
     *
     * @param dealDesc the value for b_deal_record.deal_desc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setDealDesc(String dealDesc) {
        this.dealDesc = dealDesc == null ? null : dealDesc.trim();
    }
}