package com.bob.p2p.model;

import java.io.Serializable;

public class FinanceAccountEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.ufa_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.ufa_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.ufa_available_money
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Double availableMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_finance_account
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.ufa_id
     *
     * @return the value of u_finance_account.ufa_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.ufa_id
     *
     * @param id the value for u_finance_account.ufa_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.ufa_uid
     *
     * @return the value of u_finance_account.ufa_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.ufa_uid
     *
     * @param uid the value for u_finance_account.ufa_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.ufa_available_money
     *
     * @return the value of u_finance_account.ufa_available_money
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Double getAvailableMoney() {
        return availableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.ufa_available_money
     *
     * @param availableMoney the value for u_finance_account.ufa_available_money
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setAvailableMoney(Double availableMoney) {
        this.availableMoney = availableMoney;
    }
}