package com.bob.p2p.model;

import java.io.Serializable;
import java.util.Date;

public class IncomeRecordEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_loanId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_bidId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer bidid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_bidMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Double bidmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_incomeDate
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Date incomedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_incomeMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Double incomemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bir_incomeStatus
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer incomestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_income_record
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_id
     *
     * @return the value of b_income_record.bir_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_id
     *
     * @param id the value for b_income_record.bir_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_uid
     *
     * @return the value of b_income_record.bir_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_uid
     *
     * @param uid the value for b_income_record.bir_uid
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_loanId
     *
     * @return the value of b_income_record.bir_loanId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_loanId
     *
     * @param loanid the value for b_income_record.bir_loanId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setLoanid(Integer loanid) {
        this.loanid = loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_bidId
     *
     * @return the value of b_income_record.bir_bidId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getBidid() {
        return bidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_bidId
     *
     * @param bidid the value for b_income_record.bir_bidId
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setBidid(Integer bidid) {
        this.bidid = bidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_bidMoney
     *
     * @return the value of b_income_record.bir_bidMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Double getBidmoney() {
        return bidmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_bidMoney
     *
     * @param bidmoney the value for b_income_record.bir_bidMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setBidmoney(Double bidmoney) {
        this.bidmoney = bidmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_incomeDate
     *
     * @return the value of b_income_record.bir_incomeDate
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Date getIncomedate() {
        return incomedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_incomeDate
     *
     * @param incomedate the value for b_income_record.bir_incomeDate
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setIncomedate(Date incomedate) {
        this.incomedate = incomedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_incomeMoney
     *
     * @return the value of b_income_record.bir_incomeMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Double getIncomemoney() {
        return incomemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_incomeMoney
     *
     * @param incomemoney the value for b_income_record.bir_incomeMoney
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setIncomemoney(Double incomemoney) {
        this.incomemoney = incomemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bir_incomeStatus
     *
     * @return the value of b_income_record.bir_incomeStatus
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getIncomestatus() {
        return incomestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bir_incomeStatus
     *
     * @param incomestatus the value for b_income_record.bir_incomeStatus
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setIncomestatus(Integer incomestatus) {
        this.incomestatus = incomestatus;
    }
}