package com.bob.p2p.model;

import java.io.Serializable;
import java.util.Date;

public class UserEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_phone
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_loginPassword
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private String loginpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_name
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_idCard
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_addTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_lastLoginTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.uu_headerImage
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private String headerimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_user
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_id
     *
     * @return the value of u_user.uu_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_id
     *
     * @param id the value for u_user.uu_id
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_phone
     *
     * @return the value of u_user.uu_phone
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_phone
     *
     * @param phone the value for u_user.uu_phone
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_loginPassword
     *
     * @return the value of u_user.uu_loginPassword
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public String getLoginpassword() {
        return loginpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_loginPassword
     *
     * @param loginpassword the value for u_user.uu_loginPassword
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setLoginpassword(String loginpassword) {
        this.loginpassword = loginpassword == null ? null : loginpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_name
     *
     * @return the value of u_user.uu_name
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_name
     *
     * @param name the value for u_user.uu_name
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_idCard
     *
     * @return the value of u_user.uu_idCard
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_idCard
     *
     * @param idcard the value for u_user.uu_idCard
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_addTime
     *
     * @return the value of u_user.uu_addTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_addTime
     *
     * @param addtime the value for u_user.uu_addTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_lastLoginTime
     *
     * @return the value of u_user.uu_lastLoginTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_lastLoginTime
     *
     * @param lastlogintime the value for u_user.uu_lastLoginTime
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.uu_headerImage
     *
     * @return the value of u_user.uu_headerImage
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public String getHeaderimage() {
        return headerimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.uu_headerImage
     *
     * @param headerimage the value for u_user.uu_headerImage
     *
     * @mbggenerated Thu May 27 18:45:23 CST 2021
     */
    public void setHeaderimage(String headerimage) {
        this.headerimage = headerimage == null ? null : headerimage.trim();
    }
}