package com.bob.p2p.model.loan;

import java.io.Serializable;
import java.util.Date;

public class RechargeRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.rechargeNo
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String rechargeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.rechargeStatus
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String rechargestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.rechargeMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Double rechargemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.rechargeTime
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private Date rechargetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_recharge_record.rechargeDesc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    private String rechargedesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.id
     *
     * @return the value of b_recharge_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.id
     *
     * @param id the value for b_recharge_record.id
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.uid
     *
     * @return the value of b_recharge_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.uid
     *
     * @param uid the value for b_recharge_record.uid
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.rechargeNo
     *
     * @return the value of b_recharge_record.rechargeNo
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getRechargeno() {
        return rechargeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.rechargeNo
     *
     * @param rechargeno the value for b_recharge_record.rechargeNo
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setRechargeno(String rechargeno) {
        this.rechargeno = rechargeno == null ? null : rechargeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.rechargeStatus
     *
     * @return the value of b_recharge_record.rechargeStatus
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getRechargestatus() {
        return rechargestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.rechargeStatus
     *
     * @param rechargestatus the value for b_recharge_record.rechargeStatus
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setRechargestatus(String rechargestatus) {
        this.rechargestatus = rechargestatus == null ? null : rechargestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.rechargeMoney
     *
     * @return the value of b_recharge_record.rechargeMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Double getRechargemoney() {
        return rechargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.rechargeMoney
     *
     * @param rechargemoney the value for b_recharge_record.rechargeMoney
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setRechargemoney(Double rechargemoney) {
        this.rechargemoney = rechargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.rechargeTime
     *
     * @return the value of b_recharge_record.rechargeTime
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public Date getRechargetime() {
        return rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.rechargeTime
     *
     * @param rechargetime the value for b_recharge_record.rechargeTime
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setRechargetime(Date rechargetime) {
        this.rechargetime = rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_recharge_record.rechargeDesc
     *
     * @return the value of b_recharge_record.rechargeDesc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public String getRechargedesc() {
        return rechargedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_recharge_record.rechargeDesc
     *
     * @param rechargedesc the value for b_recharge_record.rechargeDesc
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    public void setRechargedesc(String rechargedesc) {
        this.rechargedesc = rechargedesc == null ? null : rechargedesc.trim();
    }
}