package com.bob.p2p.mapper;

import com.bob.p2p.model.BorromerInfo;

public interface BorromerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int insert(BorromerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int insertSelective(BorromerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    BorromerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int updateByPrimaryKeySelective(BorromerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_borrower_info
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int updateByPrimaryKey(BorromerInfo record);
}