package com.bob.p2p.mapper;

import com.bob.p2p.model.CreditorRights;

public interface CreditorRightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int insert(CreditorRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int insertSelective(CreditorRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    CreditorRights selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int updateByPrimaryKeySelective(CreditorRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_creditor_rights
     *
     * @mbggenerated Sat May 22 18:30:38 CST 2021
     */
    int updateByPrimaryKey(CreditorRights record);
}